services:
  app:
    build: .
    container_name: triprecommendator
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - key=${key}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped