version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - key=${key}
    volumes:
      - .:/app
      - /app/node_modules
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/html
    restart: unless-stopped